services:
  - type: web
    name: routerai-backend
    runtime: node
    plan: free
    buildCommand: ../deploy-backend.sh
    startCommand: npm start
    rootDir: agentrouter-backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false